add_library(sorakado window.cc character.cc multiple_window_manager.cc single_window_manager.cc application.cc socket.cc base_character.cc image_cache.cc texture.cc texture_cache.cc default_backend_window_factory.cc popup_backend_window_factory.cc window_manager.cc util.cc font.cc sorakado.cc font_cache.cc sorakado_factory.cc ai/base_inputbox.cc ai/inputbox_window.cc ai/inputbox_info.cc ai/inputbox.cc ai/script_inputbox.cc ai/ai.cc ai/master/character.cc ai/master/ai.cc ai/master/render_info.cc ai/master/window.cc ao/context_menu.cc ao/menu_window.cc ao/menu.cc ao/ao.cc ao/master/character.cc ao/master/ao.cc ao/master/window.cc ao/master/surface.cc ao/master/element.cc ao/master/surfaces.cc ao/master/seriko.cc ao/master/actor.cc)

target_compile_options(sorakado PUBLIC -O2 -Wall)
target_compile_features(sorakado PUBLIC cxx_std_20)

find_package(jsoncpp REQUIRED)

set(INCLUDEDIRS ${PROJECT_SOURCE_DIR})
set(DEPENDENCIES ${DEPENDENCIES} jsoncpp_lib)

if (WIN32)
    set(DEPENDENCIES ${DEPENDENCIES} ws2_32)
endif()

if (UNIX)
    find_package(wayland-client REQUIRED)
    set(INCLUDEDIRS ${INCLUDEDIRS} ${WAYLAND_CLIENT_INCLUDE})
    set(DEPENDENCIES ${DEPENDENCIES} ${WAYLAND_CLIENT_LIBRARIES})
endif()

if (ENABLE_ONNXRUNTIME)
    if (WIN32)
        if (DEFINED ORT_ROOT_DIR)
            message(STATUS "OnnxRuntime enabled.")
            set(INCLUDEDIRS ${INCLUDEDIRS} ${ORT_ROOT_DIR}/include)
            set(DEPENDENCIES ${DEPENDENCIES} ${ORT_ROOT_DIR}/lib/onnxruntime.lib)
        else()
            message(STATUS "OnnxRuntime disabled.")
        endif()
    else()
        find_package(onnxruntime QUIET)
        if (onnxruntime_FOUND)
            message(STATUS "OnnxRuntime found.")
            set(DEPENDENCIES ${DEPENDENCIES} onnxruntime::onnxruntime)
            target_compile_definitions(sorakado PRIVATE USE_ONNX)
        else()
            message(STATUS "OnnxRuntime NOT found.")
        endif()
    endif()
endif()

target_include_directories(sorakado PUBLIC ${INCLUDEDIRS})
target_link_libraries(sorakado ${DEPENDENCIES})
