name: deploy sorakado-builtin.exe

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      ORT_VERSION: 1.28.0
    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        submodules: recursive
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v3
      with:
        msbuild-architecture: x64
    - name: Cache ONNX Runtime
      id: cache-ort
      uses: actions/cache@v6
      with:
        path: ${{ github.workspace }}/onnxruntime-win-x64-${{ env.ORT_VERSION }}
        key: ort-win-x64-${{ env.ORT_VERSION }}
    - name: Download and Extract ONNX Runtime
      if: steps.cache-ort.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        $Url = "https://github.com/microsoft/onnxruntime/releases/download/v${{ env.ORT_VERSION }}/onnxruntime-win-x64-${{ env.ORT_VERSION }}.zip"
        $ZipFile = "ort.zip"
        
        Write-Host "Downloading ONNX Runtime from $Url..."
        Invoke-WebRequest -Uri $Url -OutFile $ZipFile
        
        Write-Host "Extracting archive..."
        Expand-Archive -Path $ZipFile -DestinationPath ${{ github.workspace }}
        Remove-Item $ZipFile
    - name: Install Requirements
      run: |
          vcpkg install sdl3 sdl3-image sdl3-ttf jsoncpp
    - name: Build sorakado_builtin
      env:
          BUILD_ARCH: "x86-64-v3"
          CL: "/utf-8 /DUNICODE /D_UNICODE"
          CMAKE_PREFIX_PATH: ${{ github.workspace }}/onnxruntime-win-x64-${{ env.ORT_VERSION }}/lib
          CMAKE_TOOLCHAIN_FILE: C:/vcpkg/scripts/buildsystems/vcpkg.cmake
          VCPKG_ROOT: C:/vcpkg
      run: |
          cmake -S . -B build
          cmake --build build --config Release
